name: source_map_stack_trace
version: 2.1.0-nullsafety.3
description: A package for applying source maps to stack traces.
homepage: https://github.com/dart-lang/source_map_stack_trace

environment:
  # This must remain a tight constraint until nnbd is stable
  sdk: '>=2.10.0-0 <2.12.0'

dependencies:
  path: '>=1.8.0-nullsafety <1.8.0'
  stack_trace: '>=1.10.0-nullsafety <1.10.0'
  source_maps: '>=0.10.10-nullsafety <0.10.10'

dev_dependencies:
  source_span: ^1.8.0-nullsafety
  test: ^1.16.0-nullsafety
  pedantic: ^1.10.0-nullsafety
